name: hands_free_controller
description: A hands-free controller app using voice commands.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Voice Recognition
  speech_to_text: ^7.0.0
  flutter_tts: any

  # URL Launcher for opening apps/websites
  url_launcher: ^6.1.12

  # Phone call functionality
  flutter_phone_direct_caller: ^2.1.1

  # Contacts access (updated from deprecated contacts_service)
  flutter_contacts: ^1.1.7+1

  # Permissions handling
  permission_handler: ^11.0.1

  # Background service
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.0.3

  # Camera (only if you need it for future gesture features)
  camera: ^0.10.5+4

  # Local storage for settings
  shared_preferences: ^2.2.2

  # UI Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true